// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\x12\x05admin\x1a\n" +
	"user.proto\x1a\n" +
	"role.proto\x1a\x0ecustomer.proto\x1a\x10permission.proto\x1a\voauth.proto\x1a\x12organization.proto2\xc6\x11\n" +
	"\fAdminService\x12;\n" +
	"\bRegister\x12\x16.admin.RegisterRequest\x1a\x17.admin.RegisterResponse\x12J\n" +
	"\rOAuthRegister\x12\x1b.admin.OAuthRegisterRequest\x1a\x1c.admin.OAuthRegisterResponse\x12A\n" +
	"\n" +
	"OAuthToken\x12\x18.admin.OAuthTokenRequest\x1a\x19.admin.OAuthTokenResponse\x12D\n" +
	"\vOAuthVerify\x12\x19.admin.OAuthVerifyRequest\x1a\x1a.admin.OAuthVerifyResponse\x12G\n" +
	"\fOAuthRefresh\x12\x1a.admin.OAuthRefreshRequest\x1a\x1b.admin.OAuthRefreshResponse\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.admin.CreateUserRequest\x1a\x19.admin.CreateUserResponse\x128\n" +
	"\aGetUser\x12\x15.admin.GetUserRequest\x1a\x16.admin.GetUserResponse\x12A\n" +
	"\n" +
	"UpdateUser\x12\x18.admin.UpdateUserRequest\x1a\x19.admin.UpdateUserResponse\x12A\n" +
	"\n" +
	"DeleteUser\x12\x18.admin.DeleteUserRequest\x1a\x19.admin.DeleteUserResponse\x12>\n" +
	"\tListUsers\x12\x17.admin.ListUsersRequest\x1a\x18.admin.ListUsersResponse\x12M\n" +
	"\x0eCreateCustomer\x12\x1c.admin.CreateCustomerRequest\x1a\x1d.admin.CreateCustomerResponse\x12D\n" +
	"\vGetCustomer\x12\x19.admin.GetCustomerRequest\x1a\x1a.admin.GetCustomerResponse\x12M\n" +
	"\x0eUpdateCustomer\x12\x1c.admin.UpdateCustomerRequest\x1a\x1d.admin.UpdateCustomerResponse\x12M\n" +
	"\x0eDeleteCustomer\x12\x1c.admin.DeleteCustomerRequest\x1a\x1d.admin.DeleteCustomerResponse\x12J\n" +
	"\rListCustomers\x12\x1b.admin.ListCustomersRequest\x1a\x1c.admin.ListCustomersResponse\x12A\n" +
	"\n" +
	"CreateRole\x12\x18.admin.CreateRoleRequest\x1a\x19.admin.CreateRoleResponse\x128\n" +
	"\aGetRole\x12\x15.admin.GetRoleRequest\x1a\x16.admin.GetRoleResponse\x12A\n" +
	"\n" +
	"UpdateRole\x12\x18.admin.UpdateRoleRequest\x1a\x19.admin.UpdateRoleResponse\x12A\n" +
	"\n" +
	"DeleteRole\x12\x18.admin.DeleteRoleRequest\x1a\x19.admin.DeleteRoleResponse\x12>\n" +
	"\tListRoles\x12\x17.admin.ListRolesRequest\x1a\x18.admin.ListRolesResponse\x12S\n" +
	"\x10CreatePermission\x12\x1e.admin.CreatePermissionRequest\x1a\x1f.admin.CreatePermissionResponse\x12J\n" +
	"\rGetPermission\x12\x1b.admin.GetPermissionRequest\x1a\x1c.admin.GetPermissionResponse\x12S\n" +
	"\x10UpdatePermission\x12\x1e.admin.UpdatePermissionRequest\x1a\x1f.admin.UpdatePermissionResponse\x12S\n" +
	"\x10DeletePermission\x12\x1e.admin.DeletePermissionRequest\x1a\x1f.admin.DeletePermissionResponse\x12P\n" +
	"\x0fListPermissions\x12\x1d.admin.ListPermissionsRequest\x1a\x1e.admin.ListPermissionsResponse\x12Y\n" +
	"\x12CreateOrganization\x12 .admin.CreateOrganizationRequest\x1a!.admin.CreateOrganizationResponse\x12P\n" +
	"\x0fGetOrganization\x12\x1d.admin.GetOrganizationRequest\x1a\x1e.admin.GetOrganizationResponse\x12Y\n" +
	"\x12UpdateOrganization\x12 .admin.UpdateOrganizationRequest\x1a!.admin.UpdateOrganizationResponse\x12Y\n" +
	"\x12DeleteOrganization\x12 .admin.DeleteOrganizationRequest\x1a!.admin.DeleteOrganizationResponse\x12V\n" +
	"\x11ListOrganizations\x12\x1f.admin.ListOrganizationsRequest\x1a .admin.ListOrganizationsResponseB\x1eZ\x1cpersacc/api/v1/admin;adminpbb\x06proto3"

var file_admin_proto_goTypes = []any{
	(*RegisterRequest)(nil),            // 0: admin.RegisterRequest
	(*OAuthRegisterRequest)(nil),       // 1: admin.OAuthRegisterRequest
	(*OAuthTokenRequest)(nil),          // 2: admin.OAuthTokenRequest
	(*OAuthVerifyRequest)(nil),         // 3: admin.OAuthVerifyRequest
	(*OAuthRefreshRequest)(nil),        // 4: admin.OAuthRefreshRequest
	(*CreateUserRequest)(nil),          // 5: admin.CreateUserRequest
	(*GetUserRequest)(nil),             // 6: admin.GetUserRequest
	(*UpdateUserRequest)(nil),          // 7: admin.UpdateUserRequest
	(*DeleteUserRequest)(nil),          // 8: admin.DeleteUserRequest
	(*ListUsersRequest)(nil),           // 9: admin.ListUsersRequest
	(*CreateCustomerRequest)(nil),      // 10: admin.CreateCustomerRequest
	(*GetCustomerRequest)(nil),         // 11: admin.GetCustomerRequest
	(*UpdateCustomerRequest)(nil),      // 12: admin.UpdateCustomerRequest
	(*DeleteCustomerRequest)(nil),      // 13: admin.DeleteCustomerRequest
	(*ListCustomersRequest)(nil),       // 14: admin.ListCustomersRequest
	(*CreateRoleRequest)(nil),          // 15: admin.CreateRoleRequest
	(*GetRoleRequest)(nil),             // 16: admin.GetRoleRequest
	(*UpdateRoleRequest)(nil),          // 17: admin.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),          // 18: admin.DeleteRoleRequest
	(*ListRolesRequest)(nil),           // 19: admin.ListRolesRequest
	(*CreatePermissionRequest)(nil),    // 20: admin.CreatePermissionRequest
	(*GetPermissionRequest)(nil),       // 21: admin.GetPermissionRequest
	(*UpdatePermissionRequest)(nil),    // 22: admin.UpdatePermissionRequest
	(*DeletePermissionRequest)(nil),    // 23: admin.DeletePermissionRequest
	(*ListPermissionsRequest)(nil),     // 24: admin.ListPermissionsRequest
	(*CreateOrganizationRequest)(nil),  // 25: admin.CreateOrganizationRequest
	(*GetOrganizationRequest)(nil),     // 26: admin.GetOrganizationRequest
	(*UpdateOrganizationRequest)(nil),  // 27: admin.UpdateOrganizationRequest
	(*DeleteOrganizationRequest)(nil),  // 28: admin.DeleteOrganizationRequest
	(*ListOrganizationsRequest)(nil),   // 29: admin.ListOrganizationsRequest
	(*RegisterResponse)(nil),           // 30: admin.RegisterResponse
	(*OAuthRegisterResponse)(nil),      // 31: admin.OAuthRegisterResponse
	(*OAuthTokenResponse)(nil),         // 32: admin.OAuthTokenResponse
	(*OAuthVerifyResponse)(nil),        // 33: admin.OAuthVerifyResponse
	(*OAuthRefreshResponse)(nil),       // 34: admin.OAuthRefreshResponse
	(*CreateUserResponse)(nil),         // 35: admin.CreateUserResponse
	(*GetUserResponse)(nil),            // 36: admin.GetUserResponse
	(*UpdateUserResponse)(nil),         // 37: admin.UpdateUserResponse
	(*DeleteUserResponse)(nil),         // 38: admin.DeleteUserResponse
	(*ListUsersResponse)(nil),          // 39: admin.ListUsersResponse
	(*CreateCustomerResponse)(nil),     // 40: admin.CreateCustomerResponse
	(*GetCustomerResponse)(nil),        // 41: admin.GetCustomerResponse
	(*UpdateCustomerResponse)(nil),     // 42: admin.UpdateCustomerResponse
	(*DeleteCustomerResponse)(nil),     // 43: admin.DeleteCustomerResponse
	(*ListCustomersResponse)(nil),      // 44: admin.ListCustomersResponse
	(*CreateRoleResponse)(nil),         // 45: admin.CreateRoleResponse
	(*GetRoleResponse)(nil),            // 46: admin.GetRoleResponse
	(*UpdateRoleResponse)(nil),         // 47: admin.UpdateRoleResponse
	(*DeleteRoleResponse)(nil),         // 48: admin.DeleteRoleResponse
	(*ListRolesResponse)(nil),          // 49: admin.ListRolesResponse
	(*CreatePermissionResponse)(nil),   // 50: admin.CreatePermissionResponse
	(*GetPermissionResponse)(nil),      // 51: admin.GetPermissionResponse
	(*UpdatePermissionResponse)(nil),   // 52: admin.UpdatePermissionResponse
	(*DeletePermissionResponse)(nil),   // 53: admin.DeletePermissionResponse
	(*ListPermissionsResponse)(nil),    // 54: admin.ListPermissionsResponse
	(*CreateOrganizationResponse)(nil), // 55: admin.CreateOrganizationResponse
	(*GetOrganizationResponse)(nil),    // 56: admin.GetOrganizationResponse
	(*UpdateOrganizationResponse)(nil), // 57: admin.UpdateOrganizationResponse
	(*DeleteOrganizationResponse)(nil), // 58: admin.DeleteOrganizationResponse
	(*ListOrganizationsResponse)(nil),  // 59: admin.ListOrganizationsResponse
}
var file_admin_proto_depIdxs = []int32{
	0,  // 0: admin.AdminService.Register:input_type -> admin.RegisterRequest
	1,  // 1: admin.AdminService.OAuthRegister:input_type -> admin.OAuthRegisterRequest
	2,  // 2: admin.AdminService.OAuthToken:input_type -> admin.OAuthTokenRequest
	3,  // 3: admin.AdminService.OAuthVerify:input_type -> admin.OAuthVerifyRequest
	4,  // 4: admin.AdminService.OAuthRefresh:input_type -> admin.OAuthRefreshRequest
	5,  // 5: admin.AdminService.CreateUser:input_type -> admin.CreateUserRequest
	6,  // 6: admin.AdminService.GetUser:input_type -> admin.GetUserRequest
	7,  // 7: admin.AdminService.UpdateUser:input_type -> admin.UpdateUserRequest
	8,  // 8: admin.AdminService.DeleteUser:input_type -> admin.DeleteUserRequest
	9,  // 9: admin.AdminService.ListUsers:input_type -> admin.ListUsersRequest
	10, // 10: admin.AdminService.CreateCustomer:input_type -> admin.CreateCustomerRequest
	11, // 11: admin.AdminService.GetCustomer:input_type -> admin.GetCustomerRequest
	12, // 12: admin.AdminService.UpdateCustomer:input_type -> admin.UpdateCustomerRequest
	13, // 13: admin.AdminService.DeleteCustomer:input_type -> admin.DeleteCustomerRequest
	14, // 14: admin.AdminService.ListCustomers:input_type -> admin.ListCustomersRequest
	15, // 15: admin.AdminService.CreateRole:input_type -> admin.CreateRoleRequest
	16, // 16: admin.AdminService.GetRole:input_type -> admin.GetRoleRequest
	17, // 17: admin.AdminService.UpdateRole:input_type -> admin.UpdateRoleRequest
	18, // 18: admin.AdminService.DeleteRole:input_type -> admin.DeleteRoleRequest
	19, // 19: admin.AdminService.ListRoles:input_type -> admin.ListRolesRequest
	20, // 20: admin.AdminService.CreatePermission:input_type -> admin.CreatePermissionRequest
	21, // 21: admin.AdminService.GetPermission:input_type -> admin.GetPermissionRequest
	22, // 22: admin.AdminService.UpdatePermission:input_type -> admin.UpdatePermissionRequest
	23, // 23: admin.AdminService.DeletePermission:input_type -> admin.DeletePermissionRequest
	24, // 24: admin.AdminService.ListPermissions:input_type -> admin.ListPermissionsRequest
	25, // 25: admin.AdminService.CreateOrganization:input_type -> admin.CreateOrganizationRequest
	26, // 26: admin.AdminService.GetOrganization:input_type -> admin.GetOrganizationRequest
	27, // 27: admin.AdminService.UpdateOrganization:input_type -> admin.UpdateOrganizationRequest
	28, // 28: admin.AdminService.DeleteOrganization:input_type -> admin.DeleteOrganizationRequest
	29, // 29: admin.AdminService.ListOrganizations:input_type -> admin.ListOrganizationsRequest
	30, // 30: admin.AdminService.Register:output_type -> admin.RegisterResponse
	31, // 31: admin.AdminService.OAuthRegister:output_type -> admin.OAuthRegisterResponse
	32, // 32: admin.AdminService.OAuthToken:output_type -> admin.OAuthTokenResponse
	33, // 33: admin.AdminService.OAuthVerify:output_type -> admin.OAuthVerifyResponse
	34, // 34: admin.AdminService.OAuthRefresh:output_type -> admin.OAuthRefreshResponse
	35, // 35: admin.AdminService.CreateUser:output_type -> admin.CreateUserResponse
	36, // 36: admin.AdminService.GetUser:output_type -> admin.GetUserResponse
	37, // 37: admin.AdminService.UpdateUser:output_type -> admin.UpdateUserResponse
	38, // 38: admin.AdminService.DeleteUser:output_type -> admin.DeleteUserResponse
	39, // 39: admin.AdminService.ListUsers:output_type -> admin.ListUsersResponse
	40, // 40: admin.AdminService.CreateCustomer:output_type -> admin.CreateCustomerResponse
	41, // 41: admin.AdminService.GetCustomer:output_type -> admin.GetCustomerResponse
	42, // 42: admin.AdminService.UpdateCustomer:output_type -> admin.UpdateCustomerResponse
	43, // 43: admin.AdminService.DeleteCustomer:output_type -> admin.DeleteCustomerResponse
	44, // 44: admin.AdminService.ListCustomers:output_type -> admin.ListCustomersResponse
	45, // 45: admin.AdminService.CreateRole:output_type -> admin.CreateRoleResponse
	46, // 46: admin.AdminService.GetRole:output_type -> admin.GetRoleResponse
	47, // 47: admin.AdminService.UpdateRole:output_type -> admin.UpdateRoleResponse
	48, // 48: admin.AdminService.DeleteRole:output_type -> admin.DeleteRoleResponse
	49, // 49: admin.AdminService.ListRoles:output_type -> admin.ListRolesResponse
	50, // 50: admin.AdminService.CreatePermission:output_type -> admin.CreatePermissionResponse
	51, // 51: admin.AdminService.GetPermission:output_type -> admin.GetPermissionResponse
	52, // 52: admin.AdminService.UpdatePermission:output_type -> admin.UpdatePermissionResponse
	53, // 53: admin.AdminService.DeletePermission:output_type -> admin.DeletePermissionResponse
	54, // 54: admin.AdminService.ListPermissions:output_type -> admin.ListPermissionsResponse
	55, // 55: admin.AdminService.CreateOrganization:output_type -> admin.CreateOrganizationResponse
	56, // 56: admin.AdminService.GetOrganization:output_type -> admin.GetOrganizationResponse
	57, // 57: admin.AdminService.UpdateOrganization:output_type -> admin.UpdateOrganizationResponse
	58, // 58: admin.AdminService.DeleteOrganization:output_type -> admin.DeleteOrganizationResponse
	59, // 59: admin.AdminService.ListOrganizations:output_type -> admin.ListOrganizationsResponse
	30, // [30:60] is the sub-list for method output_type
	0,  // [0:30] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_user_proto_init()
	file_role_proto_init()
	file_customer_proto_init()
	file_permission_proto_init()
	file_oauth_proto_init()
	file_organization_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
