// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/v1/admin/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_v1_admin_admin_proto protoreflect.FileDescriptor

const file_api_v1_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/admin/admin.proto\x12\x05admin\x1a\x17api/v1/admin/user.proto\x1a\x17api/v1/admin/role.proto\x1a\x1bapi/v1/admin/customer.proto\x1a\x1dapi/v1/admin/permission.proto2\xed\v\n" +
	"\fAdminService\x12;\n" +
	"\bRegister\x12\x16.admin.RegisterRequest\x1a\x17.admin.RegisterResponse\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.admin.CreateUserRequest\x1a\x19.admin.CreateUserResponse\x128\n" +
	"\aGetUser\x12\x15.admin.GetUserRequest\x1a\x16.admin.GetUserResponse\x12A\n" +
	"\n" +
	"UpdateUser\x12\x18.admin.UpdateUserRequest\x1a\x19.admin.UpdateUserResponse\x12A\n" +
	"\n" +
	"DeleteUser\x12\x18.admin.DeleteUserRequest\x1a\x19.admin.DeleteUserResponse\x12>\n" +
	"\tListUsers\x12\x17.admin.ListUsersRequest\x1a\x18.admin.ListUsersResponse\x12M\n" +
	"\x0eCreateCustomer\x12\x1c.admin.CreateCustomerRequest\x1a\x1d.admin.CreateCustomerResponse\x12D\n" +
	"\vGetCustomer\x12\x19.admin.GetCustomerRequest\x1a\x1a.admin.GetCustomerResponse\x12M\n" +
	"\x0eUpdateCustomer\x12\x1c.admin.UpdateCustomerRequest\x1a\x1d.admin.UpdateCustomerResponse\x12M\n" +
	"\x0eDeleteCustomer\x12\x1c.admin.DeleteCustomerRequest\x1a\x1d.admin.DeleteCustomerResponse\x12J\n" +
	"\rListCustomers\x12\x1b.admin.ListCustomersRequest\x1a\x1c.admin.ListCustomersResponse\x12A\n" +
	"\n" +
	"CreateRole\x12\x18.admin.CreateRoleRequest\x1a\x19.admin.CreateRoleResponse\x128\n" +
	"\aGetRole\x12\x15.admin.GetRoleRequest\x1a\x16.admin.GetRoleResponse\x12A\n" +
	"\n" +
	"UpdateRole\x12\x18.admin.UpdateRoleRequest\x1a\x19.admin.UpdateRoleResponse\x12A\n" +
	"\n" +
	"DeleteRole\x12\x18.admin.DeleteRoleRequest\x1a\x19.admin.DeleteRoleResponse\x12>\n" +
	"\tListRoles\x12\x17.admin.ListRolesRequest\x1a\x18.admin.ListRolesResponse\x12S\n" +
	"\x10CreatePermission\x12\x1e.admin.CreatePermissionRequest\x1a\x1f.admin.CreatePermissionResponse\x12J\n" +
	"\rGetPermission\x12\x1b.admin.GetPermissionRequest\x1a\x1c.admin.GetPermissionResponse\x12S\n" +
	"\x10UpdatePermission\x12\x1e.admin.UpdatePermissionRequest\x1a\x1f.admin.UpdatePermissionResponse\x12S\n" +
	"\x10DeletePermission\x12\x1e.admin.DeletePermissionRequest\x1a\x1f.admin.DeletePermissionResponse\x12P\n" +
	"\x0fListPermissions\x12\x1d.admin.ListPermissionsRequest\x1a\x1e.admin.ListPermissionsResponseB\x1eZ\x1cpersacc/api/v1/admin;adminpbb\x06proto3"

var file_api_v1_admin_admin_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: admin.RegisterRequest
	(*CreateUserRequest)(nil),        // 1: admin.CreateUserRequest
	(*GetUserRequest)(nil),           // 2: admin.GetUserRequest
	(*UpdateUserRequest)(nil),        // 3: admin.UpdateUserRequest
	(*DeleteUserRequest)(nil),        // 4: admin.DeleteUserRequest
	(*ListUsersRequest)(nil),         // 5: admin.ListUsersRequest
	(*CreateCustomerRequest)(nil),    // 6: admin.CreateCustomerRequest
	(*GetCustomerRequest)(nil),       // 7: admin.GetCustomerRequest
	(*UpdateCustomerRequest)(nil),    // 8: admin.UpdateCustomerRequest
	(*DeleteCustomerRequest)(nil),    // 9: admin.DeleteCustomerRequest
	(*ListCustomersRequest)(nil),     // 10: admin.ListCustomersRequest
	(*CreateRoleRequest)(nil),        // 11: admin.CreateRoleRequest
	(*GetRoleRequest)(nil),           // 12: admin.GetRoleRequest
	(*UpdateRoleRequest)(nil),        // 13: admin.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),        // 14: admin.DeleteRoleRequest
	(*ListRolesRequest)(nil),         // 15: admin.ListRolesRequest
	(*CreatePermissionRequest)(nil),  // 16: admin.CreatePermissionRequest
	(*GetPermissionRequest)(nil),     // 17: admin.GetPermissionRequest
	(*UpdatePermissionRequest)(nil),  // 18: admin.UpdatePermissionRequest
	(*DeletePermissionRequest)(nil),  // 19: admin.DeletePermissionRequest
	(*ListPermissionsRequest)(nil),   // 20: admin.ListPermissionsRequest
	(*RegisterResponse)(nil),         // 21: admin.RegisterResponse
	(*CreateUserResponse)(nil),       // 22: admin.CreateUserResponse
	(*GetUserResponse)(nil),          // 23: admin.GetUserResponse
	(*UpdateUserResponse)(nil),       // 24: admin.UpdateUserResponse
	(*DeleteUserResponse)(nil),       // 25: admin.DeleteUserResponse
	(*ListUsersResponse)(nil),        // 26: admin.ListUsersResponse
	(*CreateCustomerResponse)(nil),   // 27: admin.CreateCustomerResponse
	(*GetCustomerResponse)(nil),      // 28: admin.GetCustomerResponse
	(*UpdateCustomerResponse)(nil),   // 29: admin.UpdateCustomerResponse
	(*DeleteCustomerResponse)(nil),   // 30: admin.DeleteCustomerResponse
	(*ListCustomersResponse)(nil),    // 31: admin.ListCustomersResponse
	(*CreateRoleResponse)(nil),       // 32: admin.CreateRoleResponse
	(*GetRoleResponse)(nil),          // 33: admin.GetRoleResponse
	(*UpdateRoleResponse)(nil),       // 34: admin.UpdateRoleResponse
	(*DeleteRoleResponse)(nil),       // 35: admin.DeleteRoleResponse
	(*ListRolesResponse)(nil),        // 36: admin.ListRolesResponse
	(*CreatePermissionResponse)(nil), // 37: admin.CreatePermissionResponse
	(*GetPermissionResponse)(nil),    // 38: admin.GetPermissionResponse
	(*UpdatePermissionResponse)(nil), // 39: admin.UpdatePermissionResponse
	(*DeletePermissionResponse)(nil), // 40: admin.DeletePermissionResponse
	(*ListPermissionsResponse)(nil),  // 41: admin.ListPermissionsResponse
}
var file_api_v1_admin_admin_proto_depIdxs = []int32{
	0,  // 0: admin.AdminService.Register:input_type -> admin.RegisterRequest
	1,  // 1: admin.AdminService.CreateUser:input_type -> admin.CreateUserRequest
	2,  // 2: admin.AdminService.GetUser:input_type -> admin.GetUserRequest
	3,  // 3: admin.AdminService.UpdateUser:input_type -> admin.UpdateUserRequest
	4,  // 4: admin.AdminService.DeleteUser:input_type -> admin.DeleteUserRequest
	5,  // 5: admin.AdminService.ListUsers:input_type -> admin.ListUsersRequest
	6,  // 6: admin.AdminService.CreateCustomer:input_type -> admin.CreateCustomerRequest
	7,  // 7: admin.AdminService.GetCustomer:input_type -> admin.GetCustomerRequest
	8,  // 8: admin.AdminService.UpdateCustomer:input_type -> admin.UpdateCustomerRequest
	9,  // 9: admin.AdminService.DeleteCustomer:input_type -> admin.DeleteCustomerRequest
	10, // 10: admin.AdminService.ListCustomers:input_type -> admin.ListCustomersRequest
	11, // 11: admin.AdminService.CreateRole:input_type -> admin.CreateRoleRequest
	12, // 12: admin.AdminService.GetRole:input_type -> admin.GetRoleRequest
	13, // 13: admin.AdminService.UpdateRole:input_type -> admin.UpdateRoleRequest
	14, // 14: admin.AdminService.DeleteRole:input_type -> admin.DeleteRoleRequest
	15, // 15: admin.AdminService.ListRoles:input_type -> admin.ListRolesRequest
	16, // 16: admin.AdminService.CreatePermission:input_type -> admin.CreatePermissionRequest
	17, // 17: admin.AdminService.GetPermission:input_type -> admin.GetPermissionRequest
	18, // 18: admin.AdminService.UpdatePermission:input_type -> admin.UpdatePermissionRequest
	19, // 19: admin.AdminService.DeletePermission:input_type -> admin.DeletePermissionRequest
	20, // 20: admin.AdminService.ListPermissions:input_type -> admin.ListPermissionsRequest
	21, // 21: admin.AdminService.Register:output_type -> admin.RegisterResponse
	22, // 22: admin.AdminService.CreateUser:output_type -> admin.CreateUserResponse
	23, // 23: admin.AdminService.GetUser:output_type -> admin.GetUserResponse
	24, // 24: admin.AdminService.UpdateUser:output_type -> admin.UpdateUserResponse
	25, // 25: admin.AdminService.DeleteUser:output_type -> admin.DeleteUserResponse
	26, // 26: admin.AdminService.ListUsers:output_type -> admin.ListUsersResponse
	27, // 27: admin.AdminService.CreateCustomer:output_type -> admin.CreateCustomerResponse
	28, // 28: admin.AdminService.GetCustomer:output_type -> admin.GetCustomerResponse
	29, // 29: admin.AdminService.UpdateCustomer:output_type -> admin.UpdateCustomerResponse
	30, // 30: admin.AdminService.DeleteCustomer:output_type -> admin.DeleteCustomerResponse
	31, // 31: admin.AdminService.ListCustomers:output_type -> admin.ListCustomersResponse
	32, // 32: admin.AdminService.CreateRole:output_type -> admin.CreateRoleResponse
	33, // 33: admin.AdminService.GetRole:output_type -> admin.GetRoleResponse
	34, // 34: admin.AdminService.UpdateRole:output_type -> admin.UpdateRoleResponse
	35, // 35: admin.AdminService.DeleteRole:output_type -> admin.DeleteRoleResponse
	36, // 36: admin.AdminService.ListRoles:output_type -> admin.ListRolesResponse
	37, // 37: admin.AdminService.CreatePermission:output_type -> admin.CreatePermissionResponse
	38, // 38: admin.AdminService.GetPermission:output_type -> admin.GetPermissionResponse
	39, // 39: admin.AdminService.UpdatePermission:output_type -> admin.UpdatePermissionResponse
	40, // 40: admin.AdminService.DeletePermission:output_type -> admin.DeletePermissionResponse
	41, // 41: admin.AdminService.ListPermissions:output_type -> admin.ListPermissionsResponse
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_admin_admin_proto_init() }
func file_api_v1_admin_admin_proto_init() {
	if File_api_v1_admin_admin_proto != nil {
		return
	}
	file_api_v1_admin_user_proto_init()
	file_api_v1_admin_role_proto_init()
	file_api_v1_admin_customer_proto_init()
	file_api_v1_admin_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_admin_admin_proto_rawDesc), len(file_api_v1_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_admin_admin_proto_goTypes,
		DependencyIndexes: file_api_v1_admin_admin_proto_depIdxs,
	}.Build()
	File_api_v1_admin_admin_proto = out.File
	file_api_v1_admin_admin_proto_goTypes = nil
	file_api_v1_admin_admin_proto_depIdxs = nil
}
