// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: vendor.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vendor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_vendor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{0}
}

func (x *Vendor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vendor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vendor) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Vendor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vendor) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Vendor) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVendorRequest) Reset() {
	*x = CreateVendorRequest{}
	mi := &file_vendor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVendorRequest) ProtoMessage() {}

func (x *CreateVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVendorRequest.ProtoReflect.Descriptor instead.
func (*CreateVendorRequest) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVendorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVendorRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CreateVendorRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *Vendor                `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVendorResponse) Reset() {
	*x = CreateVendorResponse{}
	mi := &file_vendor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVendorResponse) ProtoMessage() {}

func (x *CreateVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVendorResponse.ProtoReflect.Descriptor instead.
func (*CreateVendorResponse) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVendorResponse) GetVendor() *Vendor {
	if x != nil {
		return x.Vendor
	}
	return nil
}

type GetVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorRequest) Reset() {
	*x = GetVendorRequest{}
	mi := &file_vendor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorRequest) ProtoMessage() {}

func (x *GetVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorRequest.ProtoReflect.Descriptor instead.
func (*GetVendorRequest) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{3}
}

func (x *GetVendorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *Vendor                `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVendorResponse) Reset() {
	*x = GetVendorResponse{}
	mi := &file_vendor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVendorResponse) ProtoMessage() {}

func (x *GetVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVendorResponse.ProtoReflect.Descriptor instead.
func (*GetVendorResponse) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{4}
}

func (x *GetVendorResponse) GetVendor() *Vendor {
	if x != nil {
		return x.Vendor
	}
	return nil
}

type UpdateVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVendorRequest) Reset() {
	*x = UpdateVendorRequest{}
	mi := &file_vendor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVendorRequest) ProtoMessage() {}

func (x *UpdateVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVendorRequest.ProtoReflect.Descriptor instead.
func (*UpdateVendorRequest) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVendorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVendorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateVendorRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UpdateVendorRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        *Vendor                `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVendorResponse) Reset() {
	*x = UpdateVendorResponse{}
	mi := &file_vendor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVendorResponse) ProtoMessage() {}

func (x *UpdateVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVendorResponse.ProtoReflect.Descriptor instead.
func (*UpdateVendorResponse) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVendorResponse) GetVendor() *Vendor {
	if x != nil {
		return x.Vendor
	}
	return nil
}

type DeleteVendorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVendorRequest) Reset() {
	*x = DeleteVendorRequest{}
	mi := &file_vendor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVendorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVendorRequest) ProtoMessage() {}

func (x *DeleteVendorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVendorRequest.ProtoReflect.Descriptor instead.
func (*DeleteVendorRequest) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVendorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVendorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVendorResponse) Reset() {
	*x = DeleteVendorResponse{}
	mi := &file_vendor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVendorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVendorResponse) ProtoMessage() {}

func (x *DeleteVendorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVendorResponse.ProtoReflect.Descriptor instead.
func (*DeleteVendorResponse) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteVendorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListVendorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVendorsRequest) Reset() {
	*x = ListVendorsRequest{}
	mi := &file_vendor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVendorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVendorsRequest) ProtoMessage() {}

func (x *ListVendorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVendorsRequest.ProtoReflect.Descriptor instead.
func (*ListVendorsRequest) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{9}
}

func (x *ListVendorsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVendorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVendorsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListVendorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendors       []*Vendor              `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVendorsResponse) Reset() {
	*x = ListVendorsResponse{}
	mi := &file_vendor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVendorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVendorsResponse) ProtoMessage() {}

func (x *ListVendorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vendor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVendorsResponse.ProtoReflect.Descriptor instead.
func (*ListVendorsResponse) Descriptor() ([]byte, []int) {
	return file_vendor_proto_rawDescGZIP(), []int{10}
}

func (x *ListVendorsResponse) GetVendors() []*Vendor {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *ListVendorsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListVendorsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVendorsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_vendor_proto protoreflect.FileDescriptor

const file_vendor_proto_rawDesc = "" +
	"\n" +
	"\fvendor.proto\x12\x05admin\"\xa4\x01\n" +
	"\x06Vendor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"c\n" +
	"\x13CreateVendorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"=\n" +
	"\x14CreateVendorResponse\x12%\n" +
	"\x06vendor\x18\x01 \x01(\v2\r.admin.VendorR\x06vendor\"\"\n" +
	"\x10GetVendorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\":\n" +
	"\x11GetVendorResponse\x12%\n" +
	"\x06vendor\x18\x01 \x01(\v2\r.admin.VendorR\x06vendor\"s\n" +
	"\x13UpdateVendorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"=\n" +
	"\x14UpdateVendorResponse\x12%\n" +
	"\x06vendor\x18\x01 \x01(\v2\r.admin.VendorR\x06vendor\"%\n" +
	"\x13DeleteVendorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x14DeleteVendorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x12ListVendorsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"~\n" +
	"\x13ListVendorsResponse\x12'\n" +
	"\avendors\x18\x01 \x03(\v2\r.admin.VendorR\avendors\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x1eZ\x1cpersacc/api/v1/admin;adminpbb\x06proto3"

var (
	file_vendor_proto_rawDescOnce sync.Once
	file_vendor_proto_rawDescData []byte
)

func file_vendor_proto_rawDescGZIP() []byte {
	file_vendor_proto_rawDescOnce.Do(func() {
		file_vendor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vendor_proto_rawDesc), len(file_vendor_proto_rawDesc)))
	})
	return file_vendor_proto_rawDescData
}

var file_vendor_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_vendor_proto_goTypes = []any{
	(*Vendor)(nil),               // 0: admin.Vendor
	(*CreateVendorRequest)(nil),  // 1: admin.CreateVendorRequest
	(*CreateVendorResponse)(nil), // 2: admin.CreateVendorResponse
	(*GetVendorRequest)(nil),     // 3: admin.GetVendorRequest
	(*GetVendorResponse)(nil),    // 4: admin.GetVendorResponse
	(*UpdateVendorRequest)(nil),  // 5: admin.UpdateVendorRequest
	(*UpdateVendorResponse)(nil), // 6: admin.UpdateVendorResponse
	(*DeleteVendorRequest)(nil),  // 7: admin.DeleteVendorRequest
	(*DeleteVendorResponse)(nil), // 8: admin.DeleteVendorResponse
	(*ListVendorsRequest)(nil),   // 9: admin.ListVendorsRequest
	(*ListVendorsResponse)(nil),  // 10: admin.ListVendorsResponse
}
var file_vendor_proto_depIdxs = []int32{
	0, // 0: admin.CreateVendorResponse.vendor:type_name -> admin.Vendor
	0, // 1: admin.GetVendorResponse.vendor:type_name -> admin.Vendor
	0, // 2: admin.UpdateVendorResponse.vendor:type_name -> admin.Vendor
	0, // 3: admin.ListVendorsResponse.vendors:type_name -> admin.Vendor
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vendor_proto_init() }
func file_vendor_proto_init() {
	if File_vendor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vendor_proto_rawDesc), len(file_vendor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vendor_proto_goTypes,
		DependencyIndexes: file_vendor_proto_depIdxs,
		MessageInfos:      file_vendor_proto_msgTypes,
	}.Build()
	File_vendor_proto = out.File
	file_vendor_proto_goTypes = nil
	file_vendor_proto_depIdxs = nil
}
